### PR TITLE
FO-249 better localization in simulation

### PR DESCRIPTION
**Pull request by m-janicki**
From now on we will need to install our own fork of this package. Instructions in `harmony-robotics` to be updated.

1. disable noise on sensors 
2. increase lidar range

### CODE REVIEW

**Review by ljaniec — APPROVED** [review]
Was the choice of 100 meters as a lidar range an assumption, or is it based on some technical parameters of known lidars? I have found some lidars with 50-60 m as a range, not 100. Do we need as much? It will cripple the Gazebo simulation with a lot of data...

If this is resolved, merge it - I have no other complaints.

**Comment by m-janicki** [comment]
@ljaniec 100m is an arbitrary number, the goal here is not to simulate real lidar - goal is to provide a stable simulation with good localization. The best solution would be to have an infinite range lidar, but it is not possible.

Once we get to a point where we want to test various lidar setups (different ranges, resolutions, noise, ...) I'm happy to provide a package that allows us to parameterize all those things as a launch file parameters.

**Review by giraffe4 — COMMENTED** [review]
Looks good, but are we sure this file is the only one with the potential source of noise?

**Comment by m-janicki** [comment]
@giraffe4 
> Looks good, but are we sure this file is the only one with the potential source of noise?

I'm pretty sure this is all, but even if it is not - I've run a simulation that resulted in stable robot localization - this is what we actually need.

**Pull request merged**
